# -*- coding: utf-8 -*-
"""MLR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16VGkSYV8Q-FNO9BhpyvJfZPgCkYNDcPN

**Hafsah Shaukat**
**MTN-22-14014**
"""

import pandas as pd # data structure
import numpy as np # numerical analysis
from sklearn import linear_model # model training -- model provides
import matplotlib.pyplot as plt #Graphs plotting -- data plotting

df = pd.read_csv('/content/areaMLR.csv')
df.head()

df.bedrooms.median()

import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

df.bedrooms = df.bedrooms.fillna(median_bedrooms)

df.head()

#price = m1(area)+m2(bedrooms)+m3(age)+c

reg = linear_model.LinearRegression()
reg

reg.fit(df[['area','bedrooms','age']], df.price)

reg.coef_

reg.intercept_

reg.predict([[4300,5,40]])

a= float(input('Enter Area : '))
b= float(input('Enter No. of Bedrooms : '))
c= float(input('Enter Age : '))
price_output = reg.predict([[a,b,c]])
print("Price = ",price_output)

